name: run QA tests

on:
  workflow_dispatch:

env:
  testEnv: qa
  tokenID: ${{ secrets.TOKENID }}
  EXPIRED_TOKEN: ${{ secrets.EXPIRED_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Execute tests
        id: testrun
        run: |
          mvn test -ntp -Dkarate.env=$testEnv -Dkarate.options="--tags @initialTests"

      - name: Check if tests have run and reports are generated
        id: report-check
        if: always()
        run: |
          if [ -d "./target/cucumber-html-reports/" ];then
            echo "check=success" >> $GITHUB_OUTPUT
          fi

      - name: Publish Cucumber Report
        if: ${{ always() && steps.report-check.outputs.check == 'success' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/cucumber-html-reports
          destination_dir: "regression/${{ env.testEnv }}/${{ github.run_id }}"
          commit_message: "regression tests in ${{ env.testEnv }}: action id ${{ github.run_id }}"
          keep_files: true

